install:
  cpanm --quiet --notest Devel::Cover::Report::Coveralls Test::MockObject Test::File Test::MockTime Test::NoWarnings
language: perl
perl:
  - "5.22"
  - "5.20"
script:
    - PERL5OPT=-MDevel::Cover=-coverage,statement,branch,condition,path,subroutine prove -lrsv
    - cover
after_success:
    -cover -report coveralls
