install:
  cpanm --quiet --notest Devel::Cover::Report::Coveralls Test::MockObject
language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
script:
    - PERL5OPT=-MDevel::Cover=-coverage,statement,branch,condition,path,subroutine prove -lrsv
    - cover
after_success:
    -cover -report coveralls
